name: 🐛 Bug report
description: Use this template to report a bug or unintended behavior
title: 'Bug: '
labels: ['bug']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the following details to help us reproduce and fix it as quickly as possible.

  - type: input
    id: description
    attributes:
      label: Description (What happened?)
      placeholder: Briefly describe the bug you encountered
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: List the steps to reproduce the issue
      placeholder: |
        1. Clone the repo  
        2. Run `npm install`  
        3. Execute `npm start` and observe the error
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: Describe what actually happened (error messages, screenshots, etc.)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, library versions, hardware, etc.
      placeholder: |
        - OS: macOS Catalina 10.15.7  
        - Browser: Chrome 90.0.4430.85  
        - Node.js: v14.17.3
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other context, logs, or screenshots
      placeholder: Paste logs or screenshots here
    validations:
      required: false