name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Upload Core test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: core-test-results
        path: Core/build/reports/tests/

    - name: Upload Cli test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cli-test-results
        path: Cli/build/reports/tests/

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const run_id = context.runId;
          const run_url = `https://github.com/${owner}/${repo}/actions/runs/${run_id}`;

          if (context.payload.pull_request) {
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `❌ CI build failed! Please check [the build logs](${run_url}) for more details.`
            });
          }
